export const navigationItems = [
  "Dashboard",
  "Profiles",
  "Library",
  "Render",
  "Images",
  "Flash Image",
  "Flash Partition",
  "Media Builder",
  "Lab",
  "Import",
  "USB Devices",
  "Provisioning Server",
  "Settings",
] as const;
